<LoginScreen>:  # Definition des Login-Bildschirms



    FloatLayout:  # Utilisation de FloatLayout pour superposer les éléments



        # Définition de la couleur de fond

        canvas.before:

            Color:

                rgba: 0.7, 0.85, 1, 1 # Bleu (RGBA: Rouge, Vert, Bleu, Alpha)

            Rectangle:

                pos: self.pos

                size: self.size







        BoxLayout:  # Verwendung eines BoxLayouts für das vertikale Layout

            orientation: 'vertical'  # Legt die Orientierung des Layouts auf vertikal fest

            spacing: 10  # Abstand zwischen den Elementen

            padding: 5  # Innenabstand des Layouts



            Label:  # Erstellt ein Label zur Anzeige eines Begrüßungstextes

                text: 'Herzlich willkommen in deiner Arduino-Steuerungs-App!'  # Textinhalt des Labels

                halign: 'center'  # Horizontale Ausrichtung des Textes auf der Mitte

                valign: 'top'  # Vertikale Ausrichtung des Textes oben

                color: 0, 0, 0, 1



            TextInput:  # Textfeld zur Eingabe des Passworts

                id: password_input  # ID des TextInput-Widgets

                hint_text: 'Code Eingeben'  # Platzhaltertext, der angezeigt wird, wenn das Textfeld leer ist

                password: True  # Maskiert die Eingabe als Passwort

                multiline: False  # Erlaubt keine mehrzeilige Eingabe

                size_hint_y: None  # Keine Skalierung in der vertikalen Richtung

                height: "40dp"  # Höhe des Textfelds

                size_hint_x: 0.5  # Skalierung in der horizontalen Richtung (50% der Breite)

                pos_hint: {"center_x": 0.5}  # Zentriert das Textfeld horizontal



            Button:  # Button für die Anmeldung

                text: 'Anmelden'  # Text, der auf dem Button angezeigt wird

                on_press: root.connect(self)  # Aktion, die beim Drücken des Buttons ausgeführt wird (Verbindung herstellen)

                size_hint_y: None  # Keine Skalierung in der vertikalen Richtung

                height: "40dp"  # Höhe des Buttons

                size_hint_x: 0.5  # Skalierung in der horizontalen Richtung (50% der Breite)

                background_color: 0, 1, 0, 1  # Hintergrundfarbe des Buttons (grün)

                pos_hint: {"center_x": 0.5}  # Zentriert den Button horizontal



            Button:  # Bouton pour quitter l'application

                text: 'Schließen'

                on_press: root.quit_app()

                size_hint_y: None

                height: "40dp"

                size_hint_x: 0.5

                background_color: 1, 0, 0, 1

                pos_hint: {"center_x": 0.5}



            Label:  # Label zur Anzeige des Ergebnisses der Anmeldung

                id: result_label  # ID des Labels

                text: ''  # Initialer Textinhalt des Labels (leer)



<MainScreen>:  # Écran principal



    FloatLayout:  # Utilisation de FloatLayout pour superposer les éléments



        # Définition de la couleur de fond

        canvas.before:

            Color:

                rgba: 0, 0, 0, 1 # Bleu (RGBA: Rouge, Vert, Bleu, Alpha)

            Rectangle:

                pos: self.pos

                size: self.size





        ScrollView:  # Ajout pour permettre le défilement si nécessaire

            BoxLayout:

                orientation: 'vertical'

                spacing: 10

                padding: 10

                size_hint_y: None

                height: self.minimum_height



                Label:  # Titre principal

                    text: 'Steuerungsbereich!'

                    size_hint_y: None

                    height: "30dp"



                BoxLayout:  # Zone pour l'adresse IP

                    orientation: 'vertical'

                    spacing: 5

                    size_hint_y: None

                    height: "100dp"



                BoxLayout:  # Section de contrôle Wi-Fi

                    orientation: 'vertical'

                    spacing: 10

                    size_hint_y: None

                    height: "150dp"



                    Label:

                        text: 'Steuerung über WLAN'

                        size_hint_y: None

                        height: "20dp"



                    TextInput:

                        id: ip_address

                        hint_text: 'IP Address Eingeben'

                        multiline: False

                        size_hint_y: None

                        height: "40dp"

                        size_hint_x: 0.5

                        pos_hint: {"center_x": 0.5}



                    Label:

                        id: result_label_ip

                        text: ''

                        size_hint_y: None

                        height: "20dp"

                        color: 1, 1, 1, 1  # Rouge pour afficher une erreur







                    BoxLayout:

                        orientation: 'horizontal'

                        spacing: 5

                        size_hint_y: None

                        size_hint_x: 0.8

                        pos_hint: {"center_x": 0.5}

                        height: "40dp"



                        Button:

                            id: led_on_wifi_button

                            text: 'LED an '

                            size_hint_x: 0.5

                            height: "40dp"

                            on_press: root.turn_on_led()

                            disabled: True



                        Button:

                            id: led_off_wifi_button

                            text: 'LED aus '

                            size_hint_x: 0.5

                            height: "40dp"

                            on_press: root.turn_off_led()

                            disabled: True



                    Button:

                        id: disconnect_wifi_button

                        text: 'WLAN deaktivieren'

                        size_hint_y: None

                        height: "40dp"

                        size_hint_x: 0.5

                        pos_hint: {"center_x": 0.5}

                        on_press: root.disconnect_wifi()

                        background_color: 1, 0, 0, 1

                        disabled: True



                BoxLayout:  # Section de contrôle Bluetooth

                    orientation: 'vertical'

                    spacing: 10

                    size_hint_y: None

                    height: "200dp"



                    Label:

                        id: result_label_bluetooth

                        text: 'Steuerung über Bluetooth'

                        size_hint_y: None

                        height: "20dp"







                    Label:

                        id: bluetooth_status_label

                        text: ''

                        size_hint_y: None

                        height: "20dp"

                        color: 0, 1, 0, 1  # Texte en vert pour succès





                    BoxLayout:

                        orientation: 'horizontal'

                        spacing: 5

                        size_hint_y: None

                        size_hint_x: 0.8

                        pos_hint: {"center_x": 0.5}

                        height: "40dp"









                        Button:

                            id: connect_button

                            text: 'Verbinden'

                            size_hint_x: 0.3

                            height: "40dp"

                            on_press: app.root.get_screen('main').start_connect_device()


                            background_color: 0.5, 0.5, 0.5, 1

                            disabled: False



                        Button:

                            id: disconnect_button

                            text: 'Bluetooth Desaktivieren'

                            on_press: app.root.get_screen('main').call_disconnect_device()

                            size_hint_x: 0.4

                            height: "40dp"

                            background_color: 1, 0, 0, 1

                            disabled: True





                    BoxLayout:

                        orientation: 'horizontal'

                        spacing: 5

                        size_hint_y: None

                        size_hint_x: 0.8

                        pos_hint: {"center_x": 0.5}

                        height: "40dp"



                        Button:

                            id: led_on_button

                            text: 'LED an (Bluetooth)'

                            size_hint_x: 0.5

                            height: "40dp"

                            on_press: app.root.get_screen('main').control_led(1)

                            disabled: True



                        Button:

                            id: led_off_button

                            text: 'LED aus (Bluetooth)'

                            size_hint_x: 0.5

                            height: "40dp"

                            on_press: app.root.get_screen('main').control_led(0)  # Corrige l'appel

                            disabled: True



                Button:  # Bouton de déconnexion

                    text: 'Abmelden'

                    size_hint_y: None

                    height: "40dp"

                    size_hint_x: 0.5

                    pos_hint: {"center_x": 0.5}

                    background_color: 1, 0, 0, 1

                    on_press: root.disconnect()
